name: build package release
on:
  workflow_dispatch :
    inputs:
      release:
        description: Create a github release
        type: boolean
        required: false
        default: false

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.release == 'true' }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: get-package-version
        id: package-version
        uses: beaconbrigade/package-json-version@v0.3

      - name: download artifacts
        uses: actions/download-artifact@v3

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.package-version.outputs.version }}
          tag_name: v${{ steps.package-version.outputs.version }}
          draft: true
          prerelease: true


